### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by tilamisufff** [Deepennn/MOOC-ABSA-REC-SYS#1]
您好，很感谢您的开源项目分享！有几个问题想问下。
1、请问您进行方面级情感分析使用的是什么模型？
2、在我按照文档和项目需要导入所有库后，后端项目仍无法运行，报错问题
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1936876918 found).
  [Hint: Expected version == 0U, but received version:1936876918 != 0U:0.] (at ..\paddle\fluid\framework\lod_tensor.cc:301)
  [operator < load_combine > error]，请问您是如何运行的？

**Comment by Deepennn** [comment]
您好，感谢您对本项目的关注
1、用的模型是PaddleNLP的[unified_sentiment_extraction](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/unified_sentiment_extraction)和[multi_class](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class)，其中[unified_sentiment_extraction]用于ACOS的AOS（Aspect-Opinon-Sentiment）分析，即对评论抽取AOS元组；[multi_class]用于ACOS的C（Class）分析，即对A（Aspect）分类。
2、出现这个问题应该是因为模型文件[checkpoint](https://github.com/Deepennn/MOOC-ABSA-REC-SYS/tree/master/backend/multi_class/checkpoint)git上传时损坏，您可以提供您的邮箱地址，我将模型文件压缩包重新发送给您，您在项目中替换即可。
希望对您有所帮助：）

**Comment by tilamisufff** [comment]
好的，十分感谢！我的邮箱是1340757939@qq.com

**Comment by Deepennn** [comment]
已发送，请查收，不知道邮箱这种方式会不会导致文件损坏，如果损坏我可以试试百度网盘

**Comment by zinalgithub** [comment]
您好，请问可以求一份模型文件吗？因为在运行的时候同样遇到了这样的报错。（zn.al@qq.com）万分感谢

**Comment by zinalgithub** [comment]
> 已发送，请查收，不知道邮箱这种方式会不会导致文件损坏，如果损坏我可以试试百度网盘

您好，请问可以求一份模型文件吗？因为在运行的时候同样遇到了这样的报错。（[zn.al@qq.com](mailto:zn.al@qq.com)）万分感谢
