### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by zinalgithub** [Deepennn/MOOC-ABSA-REC-SYS#2]
您好，首先，我想感谢您的开源项目分享！我对您的项目很感兴趣，并尝试在本地运行它以了解更多细节。我遇到了一些问题，希望您能帮助我解决：
我按照您提供的文档和项目要求导入了所有必需的库，但是在尝试运行后端项目时遇到了一些问题。报错信息如下：
`ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1936876918 found).
[Hint: Expected version == 0U, but received version:1936876918 != 0U:0.] (at ..\paddle\fluid\framework\lod_tensor.cc:301)
[operator < load_combine > error]`
我已经尝试过将项目路径添加到 Python 解释器的路径中，并且成功导入了所需的模块。但是仍然无法解决这个问题。您能告诉我您是如何运行项目的吗？
非常感谢您的时间和帮助！

**Comment by Deepennn** [comment]
出现这个问题应该是因为模型文件checkpoint[https://github.com/Deepennn/MOOC-ABSA-REC-SYS/tree/master/backend/multi_class/checkpoint]git上传时损坏，我已将模型文件压缩包上传至百度网盘[链接：https://pan.baidu.com/s/1klusmEqUbKSuzYhLAclKDA?pwd=MARS 
提取码：MARS --来自百度网盘超级会员V4的分享]，解压后在项目中替换即可。
